# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 08:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('bbmdweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowDoesExtrapolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hd50_vector', utils.models.PickledFileField(blank=True, null=True, upload_to=b'')),
                ('bw_pair', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('alpha_pair', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('ahu_pair', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('ou_pair', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('bmd_analysis_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_dose_extrapolations', to='bbmdweb.BMDAnalysisModel')),
            ],
        ),
    ]
