# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-23 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbmdweb', '0002_lowdoesextrapolation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lowdoesextrapolation',
            old_name='ahu_pair',
            new_name='ufa_pair',
        ),
        migrations.RenameField(
            model_name='lowdoesextrapolation',
            old_name='alpha_pair',
            new_name='ufd_pair',
        ),
        migrations.RenameField(
            model_name='lowdoesextrapolation',
            old_name='bw_pair',
            new_name='ufh_pair',
        ),
        migrations.RenameField(
            model_name='lowdoesextrapolation',
            old_name='ou_pair',
            new_name='ufs_pair',
        ),
    ]
