# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-24 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbmdweb', '0006_auto_20171123_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowdoesextrapolation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lowdoesextrapolation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='lowdoesextrapolation',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
