# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-24 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbmdweb', '0008_lowdoesextrapolation_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowdoesextrapolation',
            name='ufa_pair',
        ),
        migrations.RemoveField(
            model_name='lowdoesextrapolation',
            name='ufd_pair',
        ),
        migrations.RemoveField(
            model_name='lowdoesextrapolation',
            name='ufh_pair',
        ),
        migrations.RemoveField(
            model_name='lowdoesextrapolation',
            name='ufs_pair',
        ),
        migrations.AddField(
            model_name='lowdoesextrapolation',
            name='ufa_m',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lowdoesextrapolation',
            name='ufa_s',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lowdoesextrapolation',
            name='ufd_m',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lowdoesextrapolation',
            name='ufd_s',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lowdoesextrapolation',
            name='ufh_m',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lowdoesextrapolation',
            name='ufh_s',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lowdoesextrapolation',
            name='ufs_m',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lowdoesextrapolation',
            name='ufs_s',
            field=models.FloatField(null=True),
        ),
    ]
